apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: jenkins-storage-class
provisioner: kubernetes.io/portworx-volume
allowVolumeExpansion: true
parameters:
   repl: "3"
   fs: "ext4"
   label: "app=jenkins"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: jenkins-data
   namespace: jenkins
   labels:
     app: jenkins
   annotations:
    px/secret-name: volume-secrets
    px/secret-namespace: portworx
spec:
   storageClassName: jenkins-storage-class
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
         fsGroup: 1000
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-data
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jenkins
