apiVersion: stork.libopenstorage.org/v1alpha1
kind: ApplicationRegistration
metadata:
  name: kafka
resources:
- PodsPath: ""
  group: kafka.cluster.confluent.io
  version: v1alpha1
  kind: KafkaCluster
  keepStatus: false
