apiVersion: v1
kind: ConfigMap
metadata:
  name: px-edge-config
data:
  config.yaml: |
    config:
      plot_lookback_hours: 336
      plot_ylimit_hum_low: 40
      plot_ylimit_hum_high: 60
      plot_ylimit_temp_low: 50
      plot_ylimit_temp_high: 100
      plot_figsize_x: 20
      plot_figsize_y: 8
      predict_lstm_units: 32
      predict_lstm_epochs: 1
      predict_lstm_batchsize: 1
      predict_lstm_activation: "sigmoid"
      predict_step: 2
      predict_tonum: 24000
      predict_fromnum: 24000
      predict_training_records: 60000
      predict_plot_figsize_x: 12
      predict_plot_figsize_y: 4
      predict_x_future_seconds: 3600
      predict_x_future_seconds_graph: 3600
      data_path: "/opt/iot/thermostat/sensor_data/edge_sensor_records.csv"
---
kind: Service
apiVersion: v1
metadata:
  name: edge-app-service
spec:
  selector:
    app: edge-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-app
  template:
    metadata:
      labels:
        app: edge-app
    spec:
      containers:
      - name: edge-app-container
        image: wallnerryan/px-edge-app:v0.2.18
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: edge-persistent-storage
          mountPath: /opt/iot/thermostat/sensor_data/
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
        resources:
          limits:
            nvidia.com/gpu: 1
      nodeSelector:
        node-type/gpu: "true"
      volumes:
      - name: edge-persistent-storage
        persistentVolumeClaim:
          claimName: px-edge-pvc
      - name: config-volume
        configMap:
          name: px-edge-config
