---
#Allow all ips
##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-edge-sc-v4-allow-all-ips
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  sharedv4: "true"
  sharedv4_svc_type: "LoadBalancer" 
  allow_all_ips: "true"
  export_options: "insecure"
allowVolumeExpansion: true
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: px-edge-pvc
spec:
  storageClassName: px-edge-sc-v4-allow-all-ips
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
