kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: elastic-pwx-storage-class
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "3"
allowVolumeExpansion: true
reclaimPolicy: Retain
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: elastic-shared-pwx-storage-class
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "3"
   shared: "true"
allowVolumeExpansion: true
reclaimPolicy: Retain
