apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-snap-data-cassandra-restored-0
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: <REPLACE-1>
spec:
  accessModes:
     - ReadWriteOnce
  storageClassName: stork-snapshot-sc
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-snap-data-cassandra-restored-1
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: <REPLACE-2>
spec:
  accessModes:
     - ReadWriteOnce
  storageClassName: stork-snapshot-sc
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-snap-data-cassandra-restored-2
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: <REPLACE-3>
spec:
  accessModes:
     - ReadWriteOnce
  storageClassName: stork-snapshot-sc
  resources:
    requests:
      storage: 10Gi
