config:
  # plot
  #hours
  plot_lookback_hours: 400
  plot_ylimit_hum_low: 40
  plot_ylimit_hum_high: 60
  plot_ylimit_temp_low: 50
  plot_ylimit_temp_high: 100
  plot_figsize_x: 20
  plot_figsize_y: 8
  # predict
  predict_step: 5
  predict_tonum: 9000
  predict_fromnum: 9000
  predict_forcastfrom: 4000
  predict_training_records: 60000
  predict_plot_figsize_x: 12
  predict_plot_figsize_y: 4
  predict_x_future_seconds: 3000
  predict_x_future_seconds_graph: 900
  # files
  #data_path: "example-data/sensor_data.csv"
  data_path: "/opt/iot/thermostat/sensor_data/edge_sensor_records.csv"
