kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: px-postgres-sc
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "1"

---

##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: postgres-data
   labels:
     app: postgres
spec:
   storageClassName: px-postgres-sc
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 5Gi
---


apiVersion: v1
kind: Secret
metadata:
  name: database-secret-config
  labels:
     app: postgres
type: Opaque
data:
  # user
  username: dXNlcg==
  # mysecretpassword
  password: bXlzZWNyZXRwYXNzd29yZA==
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
  labels:
     app: postgres
data:
  EXAMPLE_DB_HOST: postgres://postgres@postgres/example?sslmode=disable
  EXAMPLE_DB_KIND: postgres
  PGDATA: /var/lib/postgresql/data/pgdata
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
     app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      schedulerName: stork
      containers:
      - image: "postgres:12.3"
        name: postgres
        envFrom:
        - configMapRef:
            name: example-config
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database-secret-config
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret-config
              key: password
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
