kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: elastic-pwx-storage-class
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "3"
   openstorage.io/auth-secret-name: px-user-token
   openstorage.io/auth-secret-namespace: kube-system
allowVolumeExpansion: true
reclaimPolicy: Retain
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: elastic-shared-pwx-storage-class
provisioner: kubernetes.io/portworx-volume
parameters:
   openstorage.io/auth-secret-name: px-user-token
   openstorage.io/auth-secret-namespace: kube-system
   repl: "3"
   shared: "true"
allowVolumeExpansion: true
reclaimPolicy: Retain
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.14.0
  nodeSets:
  - name: default
    count: 3
    podTemplate:
      metadata:
        labels:
          appname: "elastisearch-app"
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: elastic-pwx-storage-class
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
