
config:
  # supports openshift storage, Rook/Ceph, OpenEBS, Rancher Longhorn, StorageOS
  # set to openshift, rook-ceph, openebs, longhorn, sos
  platform: "trident"
  namespace: "stress"
  # supports any SC exists within namespace
  storage_class: "netapp-ontap-iscsi"
  volumes: 50
  create_interval: 2
  # supported values: \"ReadOnlyMany\", \"ReadWriteMany\", \"ReadWriteOnce\"",
  access_mode: "ReadWriteOnce"
  # Must be in format supported by PVC
  gb_for_vol: "2Gi"
  # uses volume.beta.kubernetes.io/storage-class
  use_sc_annotation: False
  # The app that adds load per pvc (in templates/)
  load_app: "fiotools.yaml"
