apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: px-edge-rw
  region: us-east-1
  version: "1.20"
nodeGroups:
  - name: storage-nodes
    instanceType: m5.large
    minSize: 3
    maxSize: 3
    volumeSize: 40
    #ami: auto
    amiFamily: AmazonLinux2
    labels: {role: worker, "px/node-type": "storage"}
    tags:
      nodegroup-role: worker
    ssh:  
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::649513742363:policy/pxnoderole
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        cloudWatch: true
  - name: gpu-storage-nodes
    instanceType: p3.2xlarge
    minSize: 1
    maxSize: 1
    volumeSize: 40
    #ami: auto
    amiFamily: AmazonLinux2
    labels: {role: worker, "px/node-type": "gpu-storage"}
    tags:
      nodegroup-role: worker
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::649513742363:policy/pxnoderole
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        cloudWatch: true
availabilityZones: [ 'us-east-1a', 'us-east-1b', 'us-east-1c' ]
