apiVersion: apps/v1
kind: Deployment
metadata:
  name: <DEPLOYMENT_NAME>
  labels:
    purpose: testing
spec:
  selector:
    matchLabels:
      app: <DEPLOYMENT_NAME>
  replicas: 1
  template:
    metadata:
      labels:
        app: <DEPLOYMENT_NAME>
    spec:
      containers:
      - name: busybox-container
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        image: busybox
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: data
          mountPath: /myvol
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: <PERSISTENT_VOLUME_CLAIM_NAME>
