apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: px-csi-snapclass
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: pxd.portworx.com
deletionPolicy: Delete
---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: portworx-sc-repl3
provisioner: pxd.portworx.com
parameters:
  repl: "3"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-1
  annotations:
  labels:
    app-group: wordpress
    applicationgroup: wordpress-mysql
spec:
  storageClassName: portworx-sc-repl3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---

apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: portworx-sc-repl3-shared
provisioner: pxd.portworx.com
parameters:
  repl: "3"
  shared: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
    app-group: wordpress
    applicationgroup: wordpress-mysql
  annotations:
spec:
  storageClassName: portworx-sc-repl3-shared
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

